fix eks version issue

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -36,8 +36,18 @@ jobs:
         with:
           terraform_version: 1.5.7
 
+      - name: Clean Terraform Cache
+        run: |
+          rm -rf terraform/.terraform terraform/.terraform.lock.hcl
+
       - name: Terraform Init
-        run: terraform -chdir=terraform init
+        run: terraform -chdir=terraform init -upgrade
+
+      - name: Check Installed EKS Module Version
+        run: |
+          echo "Installed EKS module version:"
+          grep -A1 "terraform-aws-modules/eks/aws" terraform/.terraform.lock.hcl || echo "Module not found!"
+
 
       - name: Terraform Plan
         run: terraform -chdir=terraform plan -out=tfplan
