fix eks version issue

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -43,9 +43,7 @@ jobs:
         run: terraform -chdir=terraform init -upgrade
 
       - name: Check Installed EKS Module Version
-        run: |
-          echo "Installed EKS module version:"
-          grep -A1 "terraform-aws-modules/eks/aws" terraform/.terraform.lock.hcl || echo "Module not found!"
+        run: grep -A1 "terraform-aws-modules/eks/aws" terraform/.terraform.lock.hcl || echo "Module not found!"
 
       - name: Terraform Plan
         run: terraform -chdir=terraform plan -out=tfplan
@@ -58,7 +56,6 @@ jobs:
         if: ${{ github.event.inputs.action == 'destroy' }}
         run: terraform -chdir=terraform destroy -auto-approve
 
-      # ✅ Only run kubeconfig and kubectl when action = apply
       - name: Update kubeconfig
         if: ${{ github.event.inputs.action == 'apply' }}
         run: aws eks update-kubeconfig --name nodejs-eks --region ${{ env.AWS_REGION }}
